-- Script: Naman_SQL_Operations

-- Create database and use it
CREATE DATABASE LEARN53;
USE LEARN53;

-- Create STU table
CREATE TABLE STU (
    RNO INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    AGE INT
);

-- Insert data into STU
INSERT INTO STU (RNO, NAME, AGE) VALUES (1, 'AJAY', 13);
INSERT INTO STU VALUES (2, 'KAPIL', 12);
INSERT INTO STU (RNO, NAME) VALUES (3, 'RAM');
INSERT INTO STU (NAME, RNO, AGE) VALUES ('MOHIT', 4, 14);

-- Retrieve data from STU
SELECT RNO, NAME, AGE FROM STU;
SELECT * FROM STU;

-- Use TEST database and query EMP table
USE TEST;
SELECT * FROM EMP WHERE CITY = 'DELHI';
SELECT * FROM EMP WHERE EID = 1010;

-- LIKE - Pattern Matching
SELECT * FROM EMP WHERE NAME LIKE 'R%';
SELECT * FROM EMP WHERE NAME LIKE '%KAPOOR';
SELECT * FROM EMP WHERE ADDRESS2 LIKE '%dwarka%';
SELECT * FROM EMP WHERE NAME LIKE '_____';

-- TOP Queries
SELECT TOP 10 * FROM EMP;
SELECT TOP 3 NAME FROM EMP;

-- Back to LEARN53
USE LEARN53;

-- Update operations on STU
UPDATE STU SET AGE = 15 WHERE RNO = 3;
UPDATE STU SET AGE = 14;

-- Delete operations on STU
DELETE FROM STU WHERE RNO = 4;
DELETE FROM STU;
