

-- Alter table operations
ALTER TABLE STU ADD CLASS CHAR(4);
UPDATE STU SET CLASS = '7TH';
ALTER TABLE STU DROP COLUMN CLASS;
ALTER TABLE STU ALTER COLUMN NAME VARCHAR(20);

-- Insert additional data and drop table
INSERT INTO STU VALUES (5, 'DEEPSHIKHA', 13);
DROP TABLE STU;

-- Drop database
DROP DATABASE LEARN53;

-- Arithmetic and Logical Queries
USE TEST;
SELECT 5/2, 5%2, 5.0/2;
SELECT * FROM EMP_SAL WHERE DEPT = 'HR';
SELECT * FROM EMP_SAL WHERE DEPT <> 'OPS';
SELECT * FROM EMP_SAL WHERE SALARY > 300000;
SELECT * FROM EMP_SAL WHERE SALARY <= 50000;
SELECT * FROM EMP_SAL WHERE SALARY NOT BETWEEN 50000 AND 300000;

-- BETWEEN and IN examples
SELECT * FROM EMP_SAL WHERE SALARY BETWEEN 300000 AND 400000;
SELECT * FROM EMP_SAL WHERE DEPT IN ('IT', 'MIS', 'HR', 'ADMIN');

-- NULL and DISTINCT examples
SELECT * FROM EMP_SAL WHERE SALARY IS NULL;
SELECT DISTINCT DEPT FROM EMP_SAL;
SELECT DISTINCT DESI FROM EMP_SAL;

-- Create EMP table
USE LEARN53;
CREATE TABLE EMP (
    EID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    ADDR VARCHAR(30),
    CITY VARCHAR(20) DEFAULT 'DELHI',
    PHONE CHAR(15),
    DOB DATE,
    EMAIL VARCHAR(50)
);

-- Insert data into EMP
INSERT INTO EMP (EID, ADDR, CITY, PHONE, DOB, EMAIL)
VALUES ('E0001', 'SECTOR 11 DWARKA', 'DELHI', '9066141431', '1998-03-25', 'ABC@GMAIL.COM');
INSERT INTO EMP (EID, NAME, ADDR, CITY, PHONE, DOB, EMAIL)
VALUES ('E0002', 'PAWAN SHARMA', 'C2 JANAKPURI', 'DELHI', '9066666777', '1997-10-13', 'ABCD@GMAIL.COM');
INSERT INTO EMP (EID, NAME, ADDR, PHONE, DOB, EMAIL)
VALUES ('E0003', 'MOHIT SINGH', 'J63 RAJOURI GARDEN', '9999551147', '1996-01-01', 'MS@GMAIL.COM');
INSERT INTO EMP (EID, NAME, ADDR, CITY, PHONE, DOB, EMAIL)
VALUES ('E0004', 'AASHNA MALIK', '256 UDYOG VIHAR', 'GURGAON', '9855112200', '1999-09-26', 'AM@GMAIL.COM');

-- Update EMP table
UPDATE EMP SET NAME = 'ROHIT KUMAR';
SELECT * FROM EMP;

-- Add constraints
ALTER TABLE EMP ADD CONSTRAINT DF_CITY DEFAULT 'DELHI' FOR CITY;